services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn reelmatch_api.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 3 --access-logfile -
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DJANGO_SETTINGS_MODULE: reelmatch_api.settings
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A reelmatch_api worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: reelmatch_api.settings
    depends_on:
      - redis
      - postgres

  beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A reelmatch_api beat --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: reelmatch_api.settings
    depends_on:
      - redis
      - postgres
