# Generated by Django 4.2.7 on 2025-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=512, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('recommendation', 'Recommendation'), ('import', 'Imported')], default='manual', max_length=50)),
            ],
            options={
                'ordering': ('-added_at',),
            },
        ),
    ]
