# Generated by Django 4.2.7 on 2025-09-28 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reelmatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favoritemovie',
            index=models.Index(fields=['user', 'tmdb_id'], name='reelmatch_f_user_id_869c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritemovie',
            index=models.Index(fields=['added_at'], name='reelmatch_f_added_a_b31f39_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoritemovie',
            constraint=models.UniqueConstraint(fields=('user', 'tmdb_id'), name='unique_user_favorite'),
        ),
    ]
